package com.example.onlineshopping.contants;

public enum ErrorCode {
    USER_NOT_FOUND, OTP_FAILED, INVALID_TOKEN, OTP_NOT_FOUND, INVALID_OTP, INVALID_OTP_CODE, CATEGORY_EXISTS, CATEGORY_NOT_FOUND, PRODUCT_NOT_FOUND, USER_EXISTS
}
