# FOR ONLY LOCAL USAGE
version: "2.0"

services:
  online-shopping-database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: online-shopping
      POSTGRES_USER: online-shopping
      POSTGRES_PASSWORD: gotcha