spring:
  application:
    name: online-shopping
  mail:
    host: smtp.gmail.com
    username: ${ONLINE_SHOPPING_MAIL_USERNAME:-}
    password: ${ONLINE_SHOPPING_MAIL_USERNAME:-}
    default-encoding: UTF-8
    protocol: smtps
    port: 465