spring:
  profiles:
    active: local
  application:
    name: online-shopping
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/online-shopping
    username: online-shopping
    password: gotcha
    pool:
      enabled: true
      max-life-time: 15000
  liquibase:
    url: jdbc:postgresql://127.0.0.1:5432/online-shopping
    user: online-shopping
    password: gotcha
    enabled: true
    change-log: migration/change-log.yaml
    default-schema: public
  mail:
    host: smtp.gmail.com
    username: ${ONLINE_SHOPPING_MAIL_USERNAME:-}
    password: ${ONLINE_SHOPPING_MAIL_USERNAME:-}
    default-encoding: UTF-8
    protocol: smtps
    port: 465
#    test-connection: true
otp:
  duration: 5
springdoc:
  swagger-ui:
    enabled: true
  show-actuator: true
jwt:
  secret: ${ONLINE_SHOPPING_JWT_SECRET}
management:
  endpoints:
    web:
      exposure:
        include: "*"